import 'package:multitables/models/test_group.dart';

const PRACTICE_TEST_GROUPS = const [
  TestGroup(
    id: 'practice-0',
    title: 'Number 0',
    description: 'Multiply number 0',
    problemsClass: [0],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-1',
    title: 'Number 1',
    description: 'Multiply number 1',
    problemsClass: [1],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-2',
    title: 'Number 2',
    description: 'Multiply number 2',
    problemsClass: [2],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-3',
    title: 'Number 3',
    description: 'Multiply number 3',
    problemsClass: [3],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-123',
    title: 'Numbers 1 - 3',
    description: 'Multiply number 1, 2, 3',
    problemsClass: [1, 2, 3],
    iconImage: '',
    itemsCount: 20,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-4',
    title: 'Number 4',
    description: 'Multiply number 4',
    problemsClass: [4],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-5',
    title: 'Number 5',
    description: 'Multiply number 5',
    problemsClass: [5],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-2345',
    title: 'Numbers 2 - 5',
    description: 'Multiply number 2, 3, 4, 5',
    problemsClass: [2, 3, 4, 5],
    iconImage: '',
    itemsCount: 25,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-6',
    title: 'Number 6',
    description: 'Multiply number 6',
    problemsClass: [6],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-7',
    title: 'Number 7',
    description: 'Multiply number 7',
    problemsClass: [7],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-8',
    title: 'Number 8',
    description: 'Multiply number 8',
    problemsClass: [8],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-9',
    title: 'Number 9',
    description: 'Multiply number 9',
    problemsClass: [9],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-10',
    title: 'Number 10',
    description: 'Multiply number 10',
    problemsClass: [10],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-12345678910',
    title: 'Numbers 1 - 10',
    description: 'Multiply number from 1 to 10',
    problemsClass: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    iconImage: '',
    itemsCount: 30,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-11',
    title: 'Number 11',
    description: 'Multiply number 11',
    problemsClass: [11],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-12',
    title: 'Number 12',
    description: 'Multiply number 12',
    problemsClass: [12],
    iconImage: '',
    itemsCount: 10,
    isTimed: false,
  ),
  TestGroup(
    id: 'practice-123456789101112',
    title: 'Numbers 1 - 12',
    description: 'Multiply number from 1 to 12',
    problemsClass: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    iconImage: '',
    itemsCount: 30,
    isTimed: false,
  ),
];

const EXAM_TEST_GROUPS = [];
